### PR TITLE
Edit naming convention

### LINKED ISSUE #250: [PE-D][Tester B] The name field allows contacts to be added with numeric-only values
The application permits the addition of contacts with purely numeric names (e.g., `12345`). This is unlikely to represent valid real-world data and may result in inaccurate data entries, as such entries could arise from user typos.

Image

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #256: [PE-D][Tester D] Bug: Unable to add contacts with valid names (`addcontact`)
Given the app is to be used for managing your contact details, classes and assignments. Reasonable names of people in the relevant context should be able to be input. Valid name formats found within NUS student records are unable to be entered into the app. The following names are non-exhaustive:
1. Names containing `S/O`
2. Names containing `-`
3. Names containing brackets `(` and `)`
4. Apostrophe `'`
5. Commas `,`

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #258: [PE-D][Tester D] Bug: Unable to search for contacts with valid names (`findct`)
Given the app is to be used for managing your contact details, classes and assignments. User should be able to search for names which are considered valid in context. Valid name formats found within NUS student records throws an error shown to the user. The following names are non-exhaustive:
1. Names containing `S/O`
2. Names containing `-`
3. Names containing brackets `(` and `)`

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #262: [PE-D][Tester A] find feature can only do keyword match
### Steps
- `findcontact n/alex`
- `findcontact n/a`
- `findclass c/class`
- `findclass c/class1`

### Expected
- The first 2 commands can find the contact named `Alex Yeoh`
- The last 2 commands can find the class named `class1`
- Because sometimes users dont really remember exactly same keyword of names or class.
- There are also special cases where users name classes like `class1`, `class2`, `class3`, etc. Then the current `findcontact` does not work if users only prompted `class.

### Actual
- Only the first command can find the contact `Alex Yeoh`
- Only the last command can find the class `class1`

### Screenshots
- `findcontact n/a`

Image

- `findcontact n/alex`

Image

### Possible improvements
May consider to use pertial words match instead of keyword match, which may be more intuitive

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by ZSYUYIIE**

### CODE REVIEW

File: src/main/java/cpp/model/contact/ContactName.java [hunk 1]
```diff
@@ -11,13 +11,23 @@
 public class ContactName {
 
     public static final String MESSAGE_CONSTRAINTS = """
-            Names should only contain alphanumeric characters and spaces, and it should not be blank""";
+            Names should only contain alphanumeric characters and spaces. Special characters
```
Comment (tohyzhong) [inline src/main/java/cpp/model/contact/ContactName.java]: should use `\` so that newlines are not added when breaking the string into multiple lines
can consider separating each requirement into a new line for readability

Comment (tohyzhong) [inline src/main/java/cpp/model/contact/ContactName.java]: Should mention that names must start with alphabetic character

File: src/main/java/cpp/model/contact/ContactName.java [hunk 2]
```diff
@@ -11,13 +11,23 @@
...
+            such as hyphens (-), forward slashes (/), and parentheses () are allowed to support
```
Comment (tohyzhong) [inline src/main/java/cpp/model/contact/ContactName.java]: hyphens can only be used in between alphanumeric characters
forward slash can only be used for s/o or d/o (case-insensitive)
name should not be blank

File: src/main/java/cpp/model/contact/ContactName.java [hunk 3]
```diff
@@ -11,13 +11,23 @@
...
+     * Names must:
+     * - Start with an alphanumeric character
+     * - Contain only alphanumeric, spaces, hyphens (between alphanumeric),
+     * parentheses (with content), and s/o, d/o patterns
+     * - Hyphens must be between two alphanumeric characters (not at start/end)
+     * - Slashes only allowed in patterns: s/o, S/O, d/o, D/O
+     * - Parentheses must contain at least one alphanumeric character
      */
-    public static final String VALIDATION_REGEX = "[\\p{Alnum}][\\p{Alnum} ]*";
+    public static final String VALIDATION_REGEX = "[\\p{Alnum}]([\\p{Alnum} ]"
```
Comment (tohyzhong) [inline src/main/java/cpp/model/contact/ContactName.java]: Should start with alphabets only [A-Za-z], and no numbers allowed #250

**Review by tohyzhong — CHANGES_REQUESTED** [review]

**Review by tohyzhong — CHANGES_REQUESTED** [review]
the changes do not work well for find

if we want to find contacts based on the names in parentheses, e.g. Alex Yeoh (Alx),
`findct n/Alx` will not work,
and similarly `findct n/` parses the name as per how we parse the name for `addct`, so we can't have `(` in front

we also can't find Anne-Marie using `findct n/Anne`

Suggestion: Allow only `s/o` and `d/o` (case-insensitive), and alphanumeric characters
Disallow parentheses and `-`, but substitute the actual name with " " when doing matching

**Review by tohyzhong — APPROVED** [review]
